# Generated by Django 3.2.14 on 2023-06-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='first_release_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
